spring.application.name=curso-spring-crud-v3
spring.profiles.active=test

spring.jpa.open-in-view=false
logging.level.org.hibernate.orm.connections.pooling=OFF
logging.level.org.hibernate.engine.jdbc.env.internal=OFF
logging.level.org.hibernate.orm.jdbc=OFF